name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        debug: [debug, release]
        include:
          - os: windows-latest
            build: BiliTicketRush-${{github.ref_name}}-Windows
          - os: ubuntu-latest
            build: BiliTicketRush-${{github.ref_name}}-Linux
    runs-on: ${{ matrix.os }}
    env:
      debug: ${{ matrix.debug }}
      CARGO_TERM_COLOR: always
    steps:
    - uses: actions/checkout@v4
    - name: Build Release
      if: matrix.debug == 'release'
      run: cargo build --verbose --release
    - name: Build Debug
      if: matrix.debug == 'debug'
      run: cargo build --verbose
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
          name: ${{ matrix.debug }}-${{ matrix.build }}
          path: bili_ticket_rush/target/${{matrix.debug}}